language: python
python: 2.7
install: "pip install git+https://github.com/lektor/lektor#egg=Lektor"
script: "lektor build && lektor deploy production"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
addons:
  ssh_known_hosts: flow.srv.pocoo.org
